_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 3913f355-62f9-488e-a516-0da839bf54c4
name: Dev Newsroom
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/39
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
